version: "3.9"

services:
  product-service:
    platform: linux/x86_64
    build: spring-cloud-open-telemetry1/
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-service:14250
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_EXPORTER_PROMETHEUS_PORT=9464
    ports:
      - "8080:8080"
      - "9464:9464"

  price-service:
    platform: linux/x86_64
    build: spring-cloud-open-telemetry2/
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-service:14250
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_EXPORTER_PROMETHEUS_PORT=9465
    ports:
      - "8081"
      - "9465:9465"

  jaeger-service:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=false
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "4317"            # OTLP gRPC default port

  grafana:
    image: grafana/grafana
    container_name: grafana_1
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./platform/grafana/dashboards:/etc/grafana/provisioning/dashboards

  prometheus:
    image: prom/prometheus
    container_name: prometheus_1
    ports:
      - "9090:9090"
    volumes:
      - "./platform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
